v1.0.0
UMCUGenetics/alissa_interpret_client pull request #1
Opened 2022-02-22 10:25 UTC by rernst

2022-03-01 14:06 UTC, ellendejong requested changes

2022-03-01 14:06 UTC, ellendejong commented on README.md
> +Add this line to your the requirments file. Edit "branchname" if needed. Specific version tags and commits can also be used.
Small typo, 
requirments --> requirements.
'your' or 'the' requirements file, not both.

2022-03-01 14:06 UTC, ellendejong commented on README.md
> +git+https://github.com/UMCUGenetics/alissa_interpret_client.git@branchname#egg=alissa_interpret_client
I haven't seen addition of git to the requirements.txt previously. Can you explain what the purpose is?
Will it install any `__init__.py` aka, is this similar to `pip install -e .` ?

2022-03-01 14:06 UTC, ellendejong commented on alissa_interpret_client/alissa_interpret.py
> +        response = self.session.post(uri, data, json, **kwargs)
Will this post succeed if both variables data and json are provided?

I am used to seeing either one of them:
`data=json.dumps(json_dict)`
or 
`json=json_dict`

2022-03-01 14:06 UTC, ellendejong commented on alissa_interpret_client/alissa_interpret.py
> -        return self.session.post(uri, data, json, **kwargs).json()
Based on the variable uri, I see the api version is hardcoded to '2'. Is this done on purpose?
Are all tables available to the api supported by v2 or are some using v1 as well? Since declaration of variable `uri` has not changed and reviewed previously, feel free to ignore the comment.

2022-03-01 14:06 UTC, ellendejong commented on alissa_interpret_client/alissa_interpret.py
> +    def get_sources(self, id):
Is 'source' limited to the analysis table?
If not, i would suggest to rename this function, for example: 'get_analysis_sources'

2022-03-01 14:06 UTC, ellendejong commented on alissa_interpret_client/alissa_interpret.py
> +    def get_report(self, id):
See previous comment;
Is 'reports' limited to the analysis table?

2022-03-01 14:06 UTC, ellendejong commented on scripts/manual_review_analyses.py
> +            if header != database_columns:
Does the order of columns in the header matter? I wonder if the export fixates the order.
If not, maybe consider a different comparison, for example:

```
>>> a = [1, 2]
>>> b = [2, 1]
>>> a == b
False
>>> sorted(a) == sorted(b)
True

2022-03-01 14:06 UTC, ellendejong commented on scripts/manual_review_analyses.py
> +        help='Path to (new or existing) database file containing data from earlier export, used to skip reocuring exports.'
Typo, reocuring --> reoccurring.

2022-03-01 14:06 UTC, ellendejong commented on scripts/manual_review_analyses.py
> +if __name__ == '__main__':
The code-block under this if statement consists of quite a few code lines.
There seem to be clear separations / sub-codeblocks indicated by a comment.
Personally, I would prefer to see functions instead.

2022-03-01 14:06 UTC, ellendejong commented on scripts/manual_review_analyses.py
> +    ]
Could this be part of a settings file or argument option?

2022-03-01 14:06 UTC, ellendejong commented on scripts/manual_review_analyses.py
> +            if analysis_reference in database_analyses:
Is it necessary to extend this check that if it exists, the column/row values are identical?
Is it possible that an analysis is edited and that the analysis_reference, aka analysis id, is still the same and content has changed?

2022-03-01 14:06 UTC, ellendejong commented on scripts/manual_review_analyses.py
> +            )
The same for loop is used twice. 
Another alternative:

```
mol_var_count=0
cnv_count=0

for lab_result in analysis_data['labResults']:
    mol_var_count += lab_result['analysisVariantCount']['molecularVariantCount'] 
    cnv_count += lab_result['analysisVariantCount']['copyNumberVariationCount']
```

This comment is relevant (in my opinion) when analysis_data is a large object. Could you give some information about the `analysis_data['labResults']` object?

2022-03-01 14:06 UTC, ellendejong commented on scripts/manual_review_analyses.py
> +            # skip analysis with cnv results
I like to see the different comments :) 
Maybe it would be even more informative if the comment included information about 'why' a certain analysis is skipped.
Lines 92-95 show analysis that are skipped, with only a `continue` statement, while this example also has a print statement. What is the difference?

2022-03-01 14:06 UTC, ellendejong commented on scripts/manual_review_analyses.py
> +                continue
Between those two print statements, only  the 'flag' is different. 
Also the final print statement on lines 147+ has an overlap of the first n fields.
Is there a way to combine these? Or split variables into a variable or something?

If, at some point, you want to change the print statement, you have to change multiple lines.

2022-03-01 14:06 UTC, ellendejong commented on scripts/manual_review_analyses.py
> +                    manual_review_count[2] += 1
I would benefit from example data. 
1. Are multiple labels available for a single variant? If not, you can change it into an 'if' - 'else if'.
2. Is it possible another label is used and should there be a warning, or remaining count as 'else'?

2022-03-01 14:43 UTC, rernst commented on README.md
> +Add this line to your the requirments file. Edit "branchname" if needed. Specific version tags and commits can also be used.
fixed

2022-03-01 16:09 UTC, rernst commented on scripts/manual_review_analyses.py
> +        help='Path to (new or existing) database file containing data from earlier export, used to skip reocuring exports.'
fixed

2022-03-01 16:09 UTC, rernst commented on scripts/manual_review_analyses.py
> +                continue
Updated the sprint statement(s) after discussion.

2022-03-04 09:21 UTC, ellendejong approved these changes
Comments from previous code review have been resolved.

2022-03-04 12:30 UTC, merged